### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by ZhengXingchi** [ZhengXingchi/ZhengXingchi.github.io#64]
# 搭建开发环境
```
brew install node
brew install watchman

# 使用nrm工具切换淘宝源
npx nrm use taobao
# 如果之后需要切换回官方源可使用
npx nrm use npm

# 下载Android studio
https://developer.android.google.cn/
```

**Comment by ZhengXingchi** [comment]
# 参考文献
[React Native 入门学习笔记](https://ry09iu.github.io/web/note/2020/04/09/rn-study-note.html)

[React Native for Windows + macOS](https://microsoft.github.io/react-native-windows/)

**Comment by ZhengXingchi** [comment]
Xcode_10.2.1.xip(您使用的是 macOS 10.13.3。该应用程序要求 macOS 10.14.3 或更高版本。)
后来使用了Xcode_5.1.dmg,还是没法用，参考了[Xcode 与 macOS 系统版本的兼容问题](https://www.cnblogs.com/pinweyshg/p/5377274.html)
最后采用了Xcode_9.xip安装并放到application启动台上
[Apple官方下载地址](https://developer.apple.com/download/more/)
[iMyMac      Mac Cleaner&&免费的PDF压缩器](https://www.imymac.com/zh-CN/)

**Comment by ZhengXingchi** [comment]
# android开发平台
[android开发环境](https://developer.android.google.cn/)

**Comment by ZhengXingchi** [comment]
# 坑

1. 
```
* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> java.nio.file.AccessDeniedException: /xxxxxxx/rnapp/android/app/build/intermediates/transforms/dexBuilder/debug/0/androidx/core/R.dex
```
最后在命令行加`sudo  yarn  android`解决，本来想参考[完美解决：app:transformClassesWithDexForDebug](https://blog.csdn.net/qq_24118527/article/details/82904068)，但是好像不是一个问题，没什么帮助

**Comment by ZhengXingchi** [comment]
2. 
```
Getting these errors on initializing a new react native app:
1. Property 'passwordRules' not found on object of type 'UIView *'
2. Use of undeclared identifier 'UITextInputPasswordRules'
```

Try updating Xcode to the latest. I was stuck in Mojave so couldn't update the Xcode. But after Catalina + latest Xcode. Build worked.
Xcode 9.x definitely not gonna work with react native 0.60.0+

参考自[Property 'passwordRules' not found on object of type 'UIView<RCTBackedTextInputViewProtocol> *'](https://stackoverflow.com/questions/61279780/property-passwordrules-not-found-on-object-of-type-uiviewrctbackedtextinputv)

**Comment by ZhengXingchi** [comment]
3. Could not install the app on the device, read the error above for details.
项目根文件下运行 就是为android文件夹下的gradlew命令 添加权限
chmod 755 android/gradlew
最后记得检查下/android/local.properties，改为自己sdk位置

**Comment by ZhengXingchi** [comment]
4. A problem occurred configuring project ':app'. > failed to find Build Tools revision 28.0.1
修改/android/build.gradle文件
```
android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
   ...
```

**Comment by ZhengXingchi** [comment]
5. Could not find com.android.support:appcompat-v7:27.1.1
参考`[Could not find com.android.support:appcompat-v7:27.1.1.](https://github.com/lottie-react-native/lottie-react-native/issues/343)`
```
I had the same issue. According to this issue Could not find com.android.support:appcompat-v7:26.1.0.

In the android gradle file you need to specify the following

compileSdkVersion 26
buildToolsVersion "26.0.1"
and then find this text compile "com.android.support:appcompat-v7"
and make sure it says compile "com.android.support:appcompat-v7:26.0.1"

In your build.gradle file add maven url 'https://maven.google' should look like this

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
Rebuild your project, then this problem has been solved 😄
```

**Comment by ZhengXingchi** [comment]
6. Execution failed for task ':app:installDebug'.
参考[Gradle: Error while uploading app-local-debug.apk : Unknown failure ([CDS]close[0])](https://stackoverflow.com/questions/39518928/gradle-error-while-uploading-app-local-debug-apk-unknown-failure-cdsclose)
`[Build failed with an exception: Execution failed for task ':app:installDebug'. #15901](https://github.com/facebook/react-native/issues/15901)`

```
adb devices     
sudo  react-native run-android --deviceId emulator-5554
```

**Comment by ZhengXingchi** [comment]
7. Strict mode does not allow function declaration
参考[SyntaxError:Strict mode does not allow function declaration in a lexically nested statement.](https://blog.csdn.net/u013531824/article/details/53572821)

将react-native版本改成0.38.0能解决问题。

**Comment by ZhengXingchi** [comment]
8. requiring unknown module "0"
删除node_modules重新安装并且重启react-native run-android

**Comment by ZhengXingchi** [comment]
# ios打包

## Xcode: Missing private key
[**iOS证书(.p12)和描述文件(.mobileprovision)申请**](https://ask.dcloud.net.cn/article/152)
[**IOS Missing private key**](https://blog.csdn.net/leovnay/article/details/85703279)
[Apple开发者账号介绍及证书配置说明。](https://www.jianshu.com/p/8190cf4a8172)
[iOS 的「描述文件」是什么？](https://www.zhihu.com/question/19899208)
[iOS开发者证书和描述文件申请](https://www.cnblogs.com/wolf2008/p/10696427.html)
[一个苹果证书如何多次使用——导出p12文件](https://www.cnblogs.com/yipu/p/3617851.html)

**Comment by ZhengXingchi** [comment]
# 手动下载Xcode Simulator
[手动下载Xcode Simulator](https://www.jianshu.com/p/ddec2f028a81)

**Comment by ZhengXingchi** [comment]
# android打包
## Error: Watchman error: resolve_projpath: path
参考`[Watchman crawl failed. After MacOS Catalina Update #751](https://github.com/facebook/watchman/issues/751)`
```
To change the permissions for Watchman regarding the Documents folder, it's under Security & Privacy -> files & folders in the system preferences
```

```
Guys. I spent hours to figure this out. I found a solution.
If you still face this problem after you re-install node, watchman and expo cli etc, You gotta try this simple step. Trust me. Its all bcuz of catalina grant access to folders permission.

First, Kill all the server running and close your terminal.
Go to 'System preference' -> 'Security & Privacy' -> scroll down and click 'Full Disk Access' -> Make sure you checked on 'Terminal' and 'Watchman'. Save and restart ur laptop.

You are welcome.
```

**Comment by ZhengXingchi** [comment]
9. error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening cgjApp.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace cgjApp.xcworkspace -configuration Debug -scheme cgjApp -destination id=3C4694DD-961C-4949-BA21-2F7837EAA402 -derivedDataPath build/cgjApp

User defaults from command line:
    IDEDerivedDataPathOverride = /项目地址/ios/build/cgjApp

error: /项目地址/ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig: unable to open file (in target "NotificationService" in project "cgjApp") (in target 'NotificationService' from project 'cgjApp')
error: /项目地址/ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig: unable to open file (in target "NotificationService" in project "cgjApp") (in target 'NotificationService' from project 'cgjApp')


解决方案
```
cd ios
pod install
```

**Comment by ZhengXingchi** [comment]
10. 解决CocoaPods各种慢的方案
/user/用户名/.cocoapods/repos
